### ISSUE TITLE
[Inputs] Changing FFRAC to CANFRAC 

### ISSUE THREAD

**Issue by drnimbusrain** [noaa-oar-arl/canopy-app#106]
@angehung5 As discussed, and as described in your paper, we instead should be using the total MODIS vegfrac, i.e., "canfrac" rather than the specific  forest fraction (ffrac).

**Comment by angehung5** [comment]
Agreed, it is definitely a necessary update. Just want to clarify that total vegfrac (or green vegetation fraction) is from VIIRS, 8-day product same as LAI.
