### ISSUE TITLE
[biogenics]  Add air quality/ozone stress gamma based on GFSv16

### ISSUE THREAD

**Issue by drnimbusrain** [noaa-oar-arl/canopy-app#124]
@MaggieMarvin   This should be relatively simple addition, where we can add the MEGAN3 function for calculating "GAMMA_AQ", which depends on a current air quality index, i.e. in MEGAN3 it uses ozone W126 (ppm hours-1).  This can be calculated based on input ozone concentrations.  Initially, we can make an option for a a set constant ozone mixing ratio input in the namelist and calculate the [W126](https://www.epa.gov/sites/default/files/2015-09/documents/w126_steps_to_calculate_revised_feb19.pdf) (easier) in canopy-app, but it should be spatially dependent for regional and global scale applications, thus calculated using gridded input ozone concentrations to canopy-app (trickier).

**Comment by drnimbusrain** [comment]
Also, realized that we can add the GFS ozone mixing ratio from the 3D files, gfs.t12z.atmf*.nc (variable name = 'o3mr'), which are available on AWS as similar to the surface files (i.e.,gfs.t12z.sfcf*.nc) .  Maybe @angehung5 can help us add these first model layer ozone concentrations to the example and global canopy inputs, and update her python [global_data_process.py](https://github.com/noaa-oar-arl/canopy-app/blob/develop/python/global_data_process.py) script, we should be able to have this spatially dependent calculation of W126 ozone for input into the air quality/ozone stress gamma index.  I think we should incorporate this to canopy-app.

**Comment by drnimbusrain** [comment]
The main issue, however, is that the W126 ozone index is based on a long-term averaging, not instantaneous GFS ozone mixing ratios.  Therefore, may be best to extract the 1st model layer ozone from GFS for 2021 - 2024 and calculate the  [W126](https://www.epa.gov/sites/default/files/2015-09/documents/w126_steps_to_calculate_revised_feb19.pdf) as an offline pre-process step and add the effective climatological index to a new "canopy" variable to the example files and AWS.

**Comment by drnimbusrain** [comment]
Based on my last comment, I have now begun pulling (from AWS) and extracting the gridded, 13-km NetCDF 1st-model layer GFS ozone concentration files for entire data record (the files will be on Hopper; **//groups/NA22OAR/pcampbe8/gfsv16_ozone_w126/$yyyy/$mm/gfs.t12z.o3mr.sfc.$yyyy$mm$dd.$hhh.nc**),  and maybe @MaggieMarvin could help use Python to do the [W126 calculations](https://www.epa.gov/sites/default/files/2015-09/documents/w126_steps_to_calculate_revised_feb19.pdf) based on this and create the climatological W126 file to get the 3-year average canopy file? In fact, at the end of this week we will have exactly 3 years of gridded NetCDF hourly o3mr concentrations from start of GFSv16 record (03/23/2021 - 03/23/2024).  What a coincidence!

 In the meantime, I can add the necessary gamma ozone codes to canopy-app so that the infrastructure is ready for the gamma_aq based on MEGAN3.

**Comment by drnimbusrain** [comment]
@MaggieMarvin As discussed in today's meeting, it would be helpful if you can work on the W126 calculation using the required 3-years of GFSv16 ozone (March 22, 2021 - March 22, 2024) I extracted to Hopper at:  **/groups/NA22OAR/pcampbe8/gfsv16_ozone_w126/**

Its a relatively easy calculation, and would generate a global W126 ozone file (units of ppm hours-1).  Then we can work with Wei-Ting to add it to the external climatological canopy inputs for canopy-app.  We can then work on the canopy-app code modifications for MEGAN3-like gamma_aq factor.

**Comment by drnimbusrain** [comment]
@quaz115 As discussed, if you can add other potential gamma_aq based factors, references, and data sources here, we can see about adding them to canopy-app as options, and maybe sensitivity runs for Maggie's paper.

**Comment by drnimbusrain** [comment]
@MaggieMarvin has made progress and added the global W126 climatological calculation based on GFSv16 lowest model later ozone mixing ratios.  See last slide on the [biogenic emissions testing](https://docs.google.com/presentation/d/1ctHRwjB0bUrs0W67sQqSZnZ4M559UTfhiEI0DKyr5Vw/edit#slide=id.g2e9f9465839_0_0)
.

Due to seemingly high GFSv16 ozone concentrations, the W126 seem higher than examples provided by EPA.  @MaggieMarvin is comparing the GFS ozone against AQM and maybe other reanalysis datasets as well (e.g., CAMS).  

A copy of the file exists on Hopper at:  /groups/NA22OAR/pcampbe8/gfsv16_ozone_w126/gfsv16_ozone_w126_042021-042024.nc

@angehung5 In the meantime, it would be good if you could add these ozone W126 values to the example SE files and update README for new input in a new PR, so I can begin testing code changes to add the GAMMA_AQ to biogenic calculations.

**Comment by angehung5** [comment]
@drnimbusrain Sure, should I push the changes to the develop branch?

**Comment by drnimbusrain** [comment]
> /groups/NA22OAR/pcampbe8/gfsv16_ozone_w126/

Yes, you can make a PR to the develop branch.  Maggie may need to update the variable attributes for W126 in  the file.  We need additional ones in the variable itself, like units etc.

**Comment by angehung5** [comment]
I use "Ozone W126 index" as variable long name and "ppm-hours" as unit. Are they the right ones?

**Comment by drnimbusrain** [comment]
> I use "Ozone W126 index" as variable long name and "ppm-hours" as unit. Are they the right ones?

Yes, go ahead and base it on that and what's there.  This will facilitate my developments of adding the W126 and GAMMA_AQ variable to canopy-app biogenics.    If we update later, you could update the files too.

**Comment by drnimbusrain** [comment]
@MaggieMarvin Closing for now, but clearly we will need further understanding and possible improvement of this W126 implementation in canopy-app.  My main question is does applying the 3 year W126 climatology apply to any given canopy-app biogenic simulation in time/space?
