### ISSUE TITLE
[Inputs] Changing (CANFRAC) To Use VIIRS GVF

### ISSUE THREAD

**Issue by drnimbusrain** [noaa-oar-arl/canopy-app#133]
@angehung5 

Currently the CANFRAC is annual, but could/should be daily, or at least monthly in temporal resolution.

**Comment by drnimbusrain** [comment]
@angehung5 I update this issue to change it to the efforts in using VIIRS Greenness Vegetation Fraction (GVF) for canopy-app 'canfrac' input variable. This will also update canfrac to a higher temporal resolution (e.g., to monthly or daily).

 You can update progress here and link the eventual PR to this issue.

**Comment by angehung5** [comment]
Thanks Patrick! I am going to work on the global files and example SE files this week.
