### ISSUE TITLE
Adding NetCDF Input/Output File Options

### ISSUE THREAD

**Issue by drnimbusrain** [noaa-oar-arl/canopy-app#22]
Adding namelist controlled NetCDF input/output file options for improved assessment and testing of canopy-app modules.  

Could also make a netcdf_io module based on NACC to read netcdf inputs:  https://github.com/noaa-oar-arl/NACC/blob/master/parallel/src/netcdf_io_mod.f90 
canopy_netcdf_io_mod.F90
canopy_outncf.F90

After Issue #22 is completed, the output creation could be moved to txt and netcdf output modules:
canopy_outncf_mod.F90:   Based on NACC:  https://github.com/noaa-oar-arl/NACC/blob/master/parallel/src/outncf.f90
canopy_outtxt_mod.F90:  https://github.com/noaa-oar-arl/canopy-app/blob/develop/canopy_driver.F90#L333

For the input option, we need example input NetCDF file from Issue #25 first.  Hopefully, @angehung5 can help generate one based on the current input_variables.txt file.

@zmoon 
@drnimbusrain

**Comment by drnimbusrain** [comment]
@zmoon   One thing to consider is that with NetCDF IO we will have to compile model with  netcdf-fortran libraries.

**Comment by zmoon** [comment]
> @zmoon One thing to consider is that with NetCDF IO we will have to compile model with netcdf-fortran libraries.

Yes there is that. I do think it would be valuable to keep at least maybe a single-column text input option that doesn't require netCDF.

**Comment by drnimbusrain** [comment]
@zmoon Yes, my thought too.  

I hope this could be done by compiling with netcdf-fortran as an option (for when user wants to input/output NetCDF) rather than requirement.  I think we should keep the text file option, and add two separate input and ouput options (e.g., in_fmt and out_fmt) to namelist.   

I assume we need logic in the Makefile to compile different input (e.g., canopy_intxt_mod.F90 and canopy_inncf_mod.F90) and output submodules (e.g., canopy_outtxt_mod.F90 and canopy_outncf_mod.F90) depending on if user compiling netcdf-fortran is selected as the NetCDF read/write codes will have embedded use netcdf-fortran in them.

**Comment by zmoon** [comment]
Yeah we should be able to do that similar to the current `DEBUG` option, with conditionals and appending to `OBJS`. At some point we can move to CMake.

**Comment by drnimbusrain** [comment]
@zmoon @angehung5 Closing this issue.
