### ISSUE TITLE
Creating input variables NetCDF file for improved testing 

### ISSUE THREAD

**Issue by drnimbusrain** [noaa-oar-arl/canopy-app#25]
@angehung5   Do you think you can make an input gridded, NetCDF file that is identical to the current develop [input_variables.txt ](https://github.com/noaa-oar-arl/canopy-app/blob/develop/input_variables.txt)file?

As shown in Issue #22 , we want to also add an option in canopy-app for both inputting and outputting NetCDF gridded files  to improve testing and assessment of different modules.

**Comment by angehung5** [comment]
Sure, I definitely can do that. Just to clarify, should netCDF4 file include 1D or 2D variables? Or you want to make it flexible?

**Comment by zmoon** [comment]
I would suggest making it 2-D, since that seems more natural, but maybe we can try to design so that it would be possible to load 1-D as well

**Comment by angehung5** [comment]
OK, I will generate both 1D and 2D inputs for testing, we can determine this later

**Comment by drnimbusrain** [comment]
I like this plan @angehung5 and @zmoon.  The canopy-app may be mainly driven by 2D surface variables, but I can imagine there are some 1D variables that could be used.  

One other thing to decide is what is our NetCDF file format/convention.  We should follow some standard for both the input and optional output NetCDF (e.g., latitude, longitude, time, height, etc.) and associated variable attributes.  Maybe CF convention?  https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html

**Comment by zmoon** [comment]
Yeah for sure we should try to make nice output files, following CF, i.e. making sure all have `long_name` and `units` attrs, and adding `standard_name` when possible (i.e. when variable is in the standard name table). I also like adding `description` attr with more detailed description in some cases.

**Comment by angehung5** [comment]
yes, detailed descriptions would be helpful. I will add add them in the file.

**Comment by drnimbusrain** [comment]
@angehung5 @zmoon Closing this issue.
