### ISSUE TITLE
Refining New Input Files/Variables for UFS and Additional Canopy Processes

### ISSUE THREAD

**Issue by drnimbusrain** [noaa-oar-arl/canopy-app#41]
@angehung5 
As we move towards adding more parameterized processes in Canopy-App (e.g., bioemis, drydep, chem), we will inherently need new input variables added to the example 1D text and 1D/2D NetCDF input files for testing. 

Here is the list of new (typical atmospheric gridded model) input variables needed for now:

- Soil Type/Cat
- Surface pressure (Pa)
- Instantaneous surface downward shortwave flux (W/m2)
- Surface/Skin Temperature (K)
- 2-meter temperature (K) 
- 2-meter water vapor mixing ratio or specific humidity (kg/kg)
- Planetary Boundary Layer Height (m)
- Mass Precipitation Rate  (kg/m2 s)

We should follow exact same format as in current text and netcdf files (with attributes) in the [develop] branch as they have been standardized.  
https://github.com/noaa-oar-arl/canopy-app/blob/develop/input_variables.txt
https://github.com/noaa-oar-arl/canopy-app/blob/develop/input_variables_1D.nc
https://github.com/noaa-oar-arl/canopy-app/blob/develop/input_variables_2D.nc

We can add these new variables as we go and determine what's really needed.   You can branch off of [develop] and make PRs for subsequent additions to the files.

**Comment by drnimbusrain** [comment]
@angehung5 Please note, I have added one more variable to the list above, grid cell "soil type/category".  Thank you for your help!

**Comment by angehung5** [comment]
@drnimbusrain What do you mean "soil type/category"?

Yes, I can reformat the 2D input file and make it similar to the model input file. But I think we should keep 1D input option (only for text file maybe) for users who are only interested in point files.

**Comment by drnimbusrain** [comment]
@angehung5   See the "sotyp" variable in the GFS files or the example I sent you for UFS-SRW-App above.  It represents the dominant soil biome type for each model grid cell.      As for the 1D, yes, I only want to remove 1D NetCDF, but of course keep the 1D text and text/point option, as I agree it is very valuable.

**Comment by drnimbusrain** [comment]
@angehung5   Great discussion and seems the best way to move forward.  So we have decided to have two new input 2D NetCDF files formatted to UFS style/structure, based on GFSv16 data, but cut down to a southeast U.S. domain for ease of testing.   

The new namelist structure and filenames may then look something like this:

&FILENAMES
!2D NetCDF
met_vars    = 'gfs.t12z.sfcf000.nc' ! (GFS input) ! or phyf000.nc (UFS-SRW-App)
can_vars    = 'can.t12z.sfcf000.nc'

!1D TXT
met_vars    = 'met_variables.txt'
can_vars    = 'can_variables.txt'
!met_vars    = 'met_variables_point.txt'
!can_vars    = 'can_variables_point.txt'

Later we can adjust the input 1D text input to match the new 2D files, and include two new files..

**Comment by drnimbusrain** [comment]
@angehung5 Closing this issue.
