### ISSUE TITLE
Improved Canopy-App Directory Structure

### ISSUE THREAD

**Issue by drnimbusrain** [noaa-oar-arl/canopy-app#51]
Need for improved directory structure for Canopy-App source codes (src), example inputs (data), docs, etc.

**Comment by drnimbusrain** [comment]
@zmoon Great that you were already planning on this during your structural changes upcoming....definitely needs it.  Maybe at the same time, somewhat in conjunction with issue #31, we could add a nice header picture to the readme for Canopy-App when we come up with one... I liked what they did with the [codon example here](https://github.com/exaloop/codon).

**Comment by zmoon** [comment]
> we could add a nice header picture to the readme for Canopy-App

Yeah that would be fun. A little simpler setup, but I like the MM readme one https://github.com/NOAA-CSL/MELODIES-MONET

**Comment by drnimbusrain** [comment]
Yes, Zach!!  Can we add that with the structure overhaul?

**Comment by zmoon** [comment]
Welll someone has to make the cool logo first

**Comment by drnimbusrain** [comment]
Agreed,  and was thinking that same thing!  Hmmm...
