### ISSUE TITLE
Example input nc attrs cause many warnings on xarray open

### ISSUE THREAD

**Issue by zmoon** [noaa-oar-arl/canopy-app#55]
Currently get a bunch of warnings about the fill values.

![image](https://user-images.githubusercontent.com/15079414/231543545-9fc627bd-acc6-44d8-9c45-4a63d36283e3.png)

Although they look the same, they are different precisions (`missing_value` is float32 while `_FillValue` is float64).

![image](https://user-images.githubusercontent.com/15079414/231543824-91367275-14e3-4acc-8c6a-03da4e724194.png)

We should address this.

**Comment by drnimbusrain** [comment]
@angehung5 Can we address this issue with our inputs while you are updating the global, conus, and example SE files (as those included here in the GH repo)?

Thanks!

**Comment by angehung5** [comment]
File updated. Closing the issue.
