### ISSUE TITLE
Add Options for Improved Biogenic Emissions Calculations/Diagnostics

### ISSUE THREAD

**Issue by drnimbusrain** [noaa-oar-arl/canopy-app#70]
Incorporate crop height option to either use future GEDI measurements (i.e., issue #69 ) or user set value for crop heights (for biogenic emissions etc.).  This can be improved later.

Add an alternative biogenic emissions calculation to canopy-app that uses the canopy-averaged emission factors and the total LAI and compare that to current layerwise output integrated. Standalone [MEGAN v2.1 and v3 ](https://bai.ess.uci.edu/megan/data-and-code)do something like this.

Add a start to using a user-defined CO2 inhibition factor for ISOP only (GAMCO2), maybe gleaming from simple [HEMCO/MEGANv2.1 implementation](https://github.com/geoschem/HEMCO/blob/main/src/Extensions/hcox_megan_mod.F90).

**Comment by drnimbusrain** [comment]
@zmoon can you help provide some MEGANv2 or v3 examples of how they sum/average/integrate the canopy layers emission activity coefficients and total LAI to get total biogenic fluxes in canopy-app?  This is how I see it in MEGANv3, where they sum and weight the emission activity coefficients for temp/PAR in the different layers and later apply to LAI, right?

```
! EA response to canopy temperature/light

        IF ( Layers .EQ. 5 ) THEN
          VPGWT(1) = 0.1184635
          VPGWT(2) = 0.2393144
          VPGWT(3) = 0.284444444
          VPGWT(4) = 0.2393144
          VPGWT(5) = 0.1184635
        ELSE
          DO K = 1,Layers
          VPGWT(K) =1/Layers
          ENDDO
        ENDIF

          DO I = 1, NCOLS
            DO J = 1, NROWS

              DO K = 1, Layers
                Ea1L(K)  = CDEA(I,J,K) *
     &                GAMTLD(SunT(I,J,K),D_TEMP(I,J),S) *
     &                GAMP(SunP(I,J,K),D_PPFD(I,J)) *  SunF(I,J,K) +
     &                GAMTLD(ShaT(I,J,K),D_TEMP(I,J),S) *
     &                GAMP(ShaP(I,J,K),D_PPFD(I,J))
     &                * (1-SunF(I,J,K))

                Ea2L(K) = GAMTLI(SunT(I,J,K),S)* SunF(I,J,K)+
     &              GAMTLI(ShaT(I,J,K),S)*(1-SunF(I,J,K))

              ENDDO   ! ENDDO canopy layers
            GAMTP(I,J)=SUM((Ea1L(:)*LDFMAP(I,J) +
     &                      Ea2L(:)*(1-LDFMAP(I,J)))* VPGWT(:))
            ENDDO   ! NROWS
          ENDDO ! NCOLS
```
Then, GAMTP is applied to total LAI:
```
ER(:,:) = LAIc * GAMTP * GAMCO2 * GAMLA *
     &         GAMHW * GAMAQ * GAMHT * GAMLT * GAMSM
```


Also, as related to radiation in biogenics, what do you think about the diffuse fraction of radiation being used in the biogenics for canopy-app?  I wonder if at all possible, we could try and add that as an option.  Or, this may be fundamentally different then our implementation, as we use the downward shortwave radiation and clumping method, right?  Seems we would need to use something different, like in our HEMCO/MEGAN, with visible beam (vbdsf_ave) and  diffuse (vddsf_ave) from GFS.    I wonder if this is a source of some difference with canopy-app and HEMCO/MEGAN comparisons right now.

**Comment by zmoon** [comment]
There is method to calculate the diffuse profile as well, using a similar Beer--Lambert-type equation with an extinction coeff based on the one for the direct beam and indeed could use vddsf for top-of-canopy BC. Then if we have both profiles we could also have the diffuse fraction profile. During midday diffuse is attenuated less than beam.

**Comment by drnimbusrain** [comment]
Thanks Zach! Since your the radiation expert, do you think this would be a major source of uncertainty, and if so, maybe you  could help add both direct and diffuse (vbdsf and vddsf) fractions to biogenics?

**Comment by drnimbusrain** [comment]
@zmoon I have added bio_vert=1 option in canopy-app branch to do a MEGANv3 like summing of activity coefficients weighted equally throughout canopy and multiplying by LAI to get total kg/m2/s emissions [here.](https://github.com/noaa-oar-arl/canopy-app/commit/cf5275fdb6efbd42f53c74436953e5cbec2e6b1b)  

Original sum of  leaf-level emissions (bio_vert=0), which is summed over canopy and converted to kg/m2/s:
![image](https://github.com/noaa-oar-arl/canopy-app/assets/26631222/f32f710e-067f-4833-b3ee-f2f0c35241ae)

New MEGANv3-like canopy activity coefficient sum (bio_vert=1) from canopy-app (outputs into only top model layer:
![image](https://github.com/noaa-oar-arl/canopy-app/assets/26631222/de8482e9-387e-4552-9429-bd65d5ad970b)


@zmoon I [added a bio_vert=2 option](https://github.com/noaa-oar-arl/canopy-app/commit/e43d32bd5d5cec6c8b75076ad7dff0d3c50698cf) to do the MEGANv3-like summing based on our plant distribution function/LAD profile.   You can see as somewhat expected, it leads to a similar result to the original leaf-level emissions based on LAD (bio_vert=0; default) and then summing after:  
![image](https://github.com/noaa-oar-arl/canopy-app/assets/26631222/105175d3-9d39-4ce8-ab32-0a926690a5ff)

I think these three options are definitely still valuable in canopy-app.

**Comment by drnimbusrain** [comment]
Also added "crop_opt", which allows the user to now either use the GEDI forest canopy heights as before (crop_opt=0), which do not resolve heights from the valid crop vegetation types, or set a constant user-set value (e.g., crop_opt=1 and crop_set=3.0) for valid crop type heights.  This begins to address crop type regions in canopy-app that previously had no biogenic emissions.  This is a good start, but we are still working on getting GEDI data for crop heights, which may (or may not) exist...

Here you can see that crop_opt = 1 creates biogenic emissions in regions of vegtype defined croplands in July:

crop_opt = 0 (no cropland biogenics)
![image](https://github.com/noaa-oar-arl/canopy-app/assets/26631222/892c14f9-ebfb-4515-bb09-307fc96fb04b)

crop_opt =1 and crop_set = 3.0 (with cropland biogenics)
![image](https://github.com/noaa-oar-arl/canopy-app/assets/26631222/5cf9f641-bcc6-4100-afed-68ed9b2c1979)

**Comment by drnimbusrain** [comment]
@zmoon I switched the bio_vert options 1 and 2 as you suggested [here](https://github.com/noaa-oar-arl/canopy-app/commit/2df01845ff2fd6320bfece72badfcf3e920c8677).
