### ISSUE TITLE
[Biogenics] Adding Leaf Age response to Biogenic Emissions as per MEGAN

### ISSUE THREAD

**Issue by quaz115** [noaa-oar-arl/canopy-app#79]
The fraction of new, growing, mature, and old/senescing foliage, can be added as per Table 4 of Guenther et al., 2012 [MEGANv2.1](https://gmd.copernicus.org/articles/5/1471/2012/gmd-5-1471-2012.pdf) for different biogenic emission compounds, to start with

Need to explore any possible enhancements after seeing the result of this one.

**Comment by drnimbusrain** [comment]
@quaz115 Any progress or questions on this issue yet?  As you know the develop is now up-to-date with latest tleaf and ppfd/radiation code changes.

**Comment by quaz115** [comment]
> @quaz115 Any progress or questions on this issue yet? As you know the develop is now up-to-date with latest tleaf and ppfd/radiation code changes.

@drnimbusrain I will work on this later today, I will surely reach out with questions on code implementation as I start the implementation

**Comment by quaz115** [comment]
@drnimbusrain @MaggieMarvin @zmoon Here's an update on the code development:   https://github.com/noaa-oar-arl/canopy-app/pull/92#issue-1897451176
