### ISSUE TITLE
Missing WAF values when set flameh higher than FCH for sub-canopy/forest fires

### ISSUE THREAD

**Issue by angehung5** [noaa-oar-arl/canopy-app#82]
Canopy-app does not calculate WAF when flameh>FCH and returns missing values

     lat      lon      canheight (m)         flameh (m)    waf (1)
   34.97   276.33            27.91              27.00  4.5880087E-02
   34.97   276.33            27.91              28.00 -8.9999998E+20

In fact, if either sub- or abov-canopy type canopy-app will not calculate WAF if flameh>FCH. It would be better to show an alert and use WAF=1 when flameh>FCH. But seems something wrong with above-canopy case which should use flameh+FCH in the calculation.

**Comment by drnimbusrain** [comment]
Actually, this is due to the requirement that the flameh must be </= FCH for both sub- and above-canopy cases.  It could be improved and make this requirement only for sub-canopy type, and also printing a warning and forcing WAF=1 in this case as the flame truly cannot be higher than canopy height in sub-canopy type.

**Comment by drnimbusrain** [comment]
@angehung5 Please see and test my [updated branch fix/waf_flameh](https://github.com/noaa-oar-arl/canopy-app/tree/fix/waf_flameh), which has been linked here.  Can you report back here with your updated WAF testing with this branch?  Thanks!

**Comment by angehung5** [comment]
It works well. Thanks Patrick @drnimbusrain 

     lat      lon      canheight (m)         flameh (m)    waf (1)
   34.97   276.33            27.91            27.00  4.5880087E-02
   34.97   276.33            27.91            28.00  1.0000000E+00

Issue closed.
